### PR TITLE
DEVX-3237 Language and style parameters

### PR DESCRIPTION
**Pull request by vshisterov**
Updating the sample with new language and style parameters

### CODE REVIEW

**Review by lornajane — CHANGES_REQUESTED** [review]
Can I get a bit more context on this change? We use this example in a few of our documentation pages and demos, and I can't see these alternative parameters as part of the main docs yet. Is this change live, and does the PR here need to land at the same time as other documentation changes?

**Comment by vshisterov** [comment]
sure, it's related to new Voice Talk action API, which is already live, still the docs is not yet published, I have opened two PRs for that:
* https://github.com/Nexmo/nexmo-developer/pull/3079 for guides and NCCO Reference;
* https://github.com/Nexmo/api-specification/pull/350 for API Reference

**Comment by hummusonrails** [comment]
Let's hold off on merging this until we work through the complementary PRs in the API specs and NDP

**Comment by vshisterov** [comment]
hi @lornajane , @bencgreenberg , can we probably now proceed with this change? we have all the styles published now.

**Comment by hummusonrails** [comment]
Yes, this is well ready, thanks for the shout, @vshisterov! The rest of the docs have all been updated at this point.

**Review by hummusonrails — APPROVED** [review]

**Comment by hummusonrails** [comment]
I'm going to hold off on merging though until we circle back with @lornajane to make sure she's on board here as well.

**Review by lornajane — APPROVED** [review]
Great! Time to merge :)

**Pull request merged**
